title: The Consultants' Circle
description: Consulting Network
site_title: 'The Consultant\'s Circle'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: theconsultantscircle
email: theconsultantscircle@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
